[package]
name = "image-organize"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
image = "0.25.5"
rfd = "0.15.2"
image-webp = "0.1.3"
egui_extras = { version = "0.30.0", features = ["all_loaders"] }
